#!/bin/bash
# kklass_compiler.sh - Compile class definitions to optimized bash code
# Usage: bash kklass_compiler.sh input.kk output.sh

KKLASS_COMPILER_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
source "$KKLASS_COMPILER_DIR/kklass.sh"

kk.compiler._collect_classes() {
    local output_array_name="$1"
    local -n output_ref="$output_array_name"
    local function_name=""

    output_ref=()
    while IFS= read -r function_name; do
        if [[ "$function_name" == *.new ]]; then
            output_ref+=("${function_name%.new}")
        fi
    done < <(compgen -A function)
}

# Emit `declare -p NAME` for every variable NAME, rewritten to declare into the
# GLOBAL scope: a compiled file is commonly sourced from inside a function
# (autoloadClasses), where a plain `declare -a` would create a local.
kk.compiler._dump_vars() {
    local output_file="$1"
    shift
    local var_name declaration
    for var_name in "$@"; do
        declaration="$(declare -p "$var_name" 2>/dev/null)" || continue
        declaration="${declaration/declare -a /declare -ga }"
        declaration="${declaration/declare -A /declare -gA }"
        declaration="${declaration/declare -- /declare -g }"
        declaration="${declaration/declare -i /declare -gi }"
        printf '%s\n' "$declaration" >> "$output_file"
    done
}

# Compile = DUMP. The classes are built in this process by the normal runtime
# (source the input), then every `<Class>_*` variable and every `<Class>.*`
# function is written out verbatim with `declare -p` / `declare -f`. There is
# no second code generator to keep in sync with kklass.sh (F4 was exactly that
# drift: owner-less cache, missing tables, an old static-method shape): whatever
# the runtime builds — templates, owner maps, caches, static wrappers, the
# .new/.constructor pair, decl tables for later subclassing — is what loads.
compile_class_file() {
    local input_file="$1"
    local output_file="$2"
    local source_file="$input_file"
    local translated_input=""
    local source_label="$input_file"

    [[ ! -f "$input_file" ]] && { echo "Error: Input file not found: $input_file" >&2; return 1; }

    if [[ "$input_file" == *.kkp ]]; then
        translated_input="$(mktemp)" || return 1
        bash "$KKLASS_COMPILER_DIR/kklass_kkp.sh" "$input_file" "$translated_input" || {
            rm -f "$translated_input"
            return 1
        }
        source_file="$translated_input"
    fi

    # Build the classes in THIS shell. Loud: the input's stderr goes through and
    # a failing input aborts the compile instead of producing a half-empty file.
    local source_rc
    source "$source_file"; source_rc=$?
    if (( source_rc != 0 )); then
        rm -f "$translated_input"
        echo "Error: sourcing $input_file failed with status $source_rc; nothing compiled" >&2
        return 1
    fi

    local class_list=()
    kk.compiler._collect_classes class_list

    [[ ${#class_list[@]} -eq 0 ]] && {
        rm -f "$translated_input"
        echo "Error: No classes found in $input_file" >&2
        return 1
    }

    cat > "$output_file" <<HEADER
#!/bin/bash
# Auto-generated by kklass_compiler.sh
# DO NOT EDIT MANUALLY - Changes will be overwritten
# A verbatim dump (declare -p / declare -f) of the classes the runtime built
# from the source file; load with `source`.

source "$KKLASS_COMPILER_DIR/kklass.sh"

HEADER

    local class_name var_name fn_name
    local -a var_names fn_names
    for class_name in "${class_list[@]}"; do
        {
            echo ""
            echo "# ===== Class: $class_name ====="
        } >> "$output_file"

        # Every <Class>_* variable: metadata tables, method bodies, static
        # state, the instance template, the decl tables.
        var_names=()
        while IFS= read -r var_name; do
            [[ -n "$var_name" ]] && var_names+=("$var_name")
        done < <(compgen -A variable "${class_name}_")
        kk.compiler._dump_vars "$output_file" "${var_names[@]}"

        # Every <Class>.* function: .new (and the abstract-guard wrapper's
        # __decl_new_impl), .constructor, static accessors, static methods and
        # their __static_ bodies.
        fn_names=()
        while IFS= read -r fn_name; do
            [[ -n "$fn_name" ]] && fn_names+=("$fn_name")
        done < <(compgen -A function "${class_name}.")
        for fn_name in "${fn_names[@]}"; do
            declare -f "$fn_name" >> "$output_file"
        done
    done

    cat >> "$output_file" <<EOF

# Compiled classes: ${class_list[*]}
# Generated: $(date)
# Source: $source_label
EOF

    chmod +x "$output_file"
    rm -f "$translated_input"

    echo "✓ Compiled ${#class_list[@]} classes to: $output_file"
    echo "  Classes: ${class_list[*]}"
    echo "  Usage: source $output_file && ClassName.new instance_name"
}

# Main
if [[ $# -lt 2 ]]; then
    cat <<'USAGE'
Usage: bash kklass_compiler.sh <input.kk> <output.sh>

Compiles class definitions from input file into optimized bash code.

Example:
    # Compile classes
    bash kklass_compiler.sh my_classes.kk my_classes_compiled.sh
    
    # Use compiled classes
    source my_classes_compiled.sh
    MyClass.new myobj
    myobj.method_name
USAGE
    exit 1
fi

compile_class_file "$1" "$2"
