#!/bin/bash
# kklass_compiler.sh - Compile class definitions to optimized bash code
# Usage: bash kklass_compiler.sh input.kk output.sh

KKLASS_COMPILER_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
source "$KKLASS_COMPILER_DIR/kklass.sh"

kk.compiler._export_decl_if_exists() {
    local output_file="$1"
    local var_name="$2"
    local declaration=""

    if ! declare -p "$var_name" &>/dev/null; then
        return 0
    fi

    declaration="$(declare -p "$var_name")"
    declaration="${declaration/declare -a /declare -ga }"
    declaration="${declaration/declare -A /declare -gA }"
    declaration="${declaration/declare -- /declare -g }"
    printf '%s\n' "$declaration" >> "$output_file"
}

kk.compiler._collect_classes() {
    local output_array_name="$1"
    local -n output_ref="$output_array_name"
    local function_name=""

    output_ref=()
    while IFS= read -r function_name; do
        if [[ "$function_name" == *.new ]]; then
            output_ref+=("${function_name%.new}")
        fi
    done < <(compgen -A function)
}

compile_class_file() {
    local input_file="$1"
    local output_file="$2"
    local source_file="$input_file"
    local translated_input=""
    local source_label="$input_file"
    
    [[ ! -f "$input_file" ]] && { echo "Error: Input file not found: $input_file" >&2; return 1; }

    if [[ "$input_file" == *.kkp ]]; then
        translated_input="$(mktemp)" || return 1
        bash "$KKLASS_COMPILER_DIR/kklass_kkp.sh" "$input_file" "$translated_input" || {
            rm -f "$translated_input"
            return 1
        }
        source_file="$translated_input"
    fi
    
    # Source input file to create classes in current shell
    source "$source_file" >/dev/null 2>&1
    
    # Get all defined classes by finding .new functions
    local class_list=()
    kk.compiler._collect_classes class_list
    
    [[ ${#class_list[@]} -eq 0 ]] && {
        rm -f "$translated_input"
        echo "Error: No classes found in $input_file" >&2
        return 1
    }
    
    # Create output file with header
    cat > "$output_file" <<HEADER
#!/bin/bash
# Auto-generated by kklass_compiler.sh
# DO NOT EDIT MANUALLY - Changes will be overwritten

source "$KKLASS_COMPILER_DIR/kklass.sh"

HEADER
    
    echo "# Class metadata and constructors" >> "$output_file"
    
    # Export each class
    for class_name in "${class_list[@]}"; do
        {
            echo ""
            echo "# ===== Class: $class_name ====="
            
            # Export properties array
            local props_var="${class_name}_class_properties"
            kk.compiler._export_decl_if_exists "$output_file" "$props_var"
            
            # Export methods array
            local meths_var="${class_name}_class_methods"
            kk.compiler._export_decl_if_exists "$output_file" "$meths_var"

            # Export static member arrays and metadata if present
            kk.compiler._export_decl_if_exists "$output_file" "${class_name}_class_static_properties"
            kk.compiler._export_decl_if_exists "$output_file" "${class_name}_class_static_methods"
            kk.compiler._export_decl_if_exists "$output_file" "${class_name}_class_static_property_owner"
            kk.compiler._export_decl_if_exists "$output_file" "${class_name}_class_static_method_owner"
            kk.compiler._export_decl_if_exists "$output_file" "${class_name}_computed_getters"
            kk.compiler._export_decl_if_exists "$output_file" "${class_name}_computed_setters"
            kk.compiler._export_decl_if_exists "$output_file" "${class_name}_method_virtual"
            kk.compiler._export_decl_if_exists "$output_file" "${class_name}_method_override"
            kk.compiler._export_decl_if_exists "$output_file" "${class_name}_method_abstract"
            kk.compiler._export_decl_if_exists "$output_file" "${class_name}_method_visibility"
            kk.compiler._export_decl_if_exists "$output_file" "${class_name}_method_owner"
            kk.compiler._export_decl_if_exists "$output_file" "${class_name}_property_visibility"
            kk.compiler._export_decl_if_exists "$output_file" "${class_name}_property_owner"
            
            # Export parent class
            local parent_var="${class_name}_parent_class"
            local parent_val="${!parent_var}"
            printf "declare -g %s=%q\n" "$parent_var" "$parent_val"

            # Export class abstract flag and constructor body
            local abstract_var="${class_name}_class_abstract"
            printf "declare -g %s=%q\n" "$abstract_var" "${!abstract_var:-0}"
            local constructor_var="${class_name}_constructor_body"
            if declare -p "$constructor_var" &>/dev/null; then
                printf "declare -g %s=%q\n" "$constructor_var" "${!constructor_var}"
            fi
            
            # Export method cache
            echo "declare -gA ${class_name}_method_cache"
            
            # Export method bodies
            local -n meths_ref="$meths_var" 2>/dev/null
            if [[ -n "${meths_ref[@]}" ]]; then
                for m in "${meths_ref[@]}"; do
                    local body_var="${class_name}_method_body_${m}"
                    printf "declare -g %s=%q\n" "$body_var" "${!body_var}"
                    
                    # Pre-populate cache
                    echo "${class_name}_method_cache[\"${m}\"]=\"${class_name}\""
                done
            fi

            # Export static member state and static method bodies
            local static_props_var="${class_name}_class_static_properties"
            local static_prop_owner_var="${class_name}_class_static_property_owner"
            if declare -p "$static_props_var" &>/dev/null; then
                local -n static_props_ref="$static_props_var"
                local -n static_prop_owner_ref="$static_prop_owner_var"
                local sp
                for sp in "${static_props_ref[@]}"; do
                    local static_owner="${static_prop_owner_ref[$sp]:-$class_name}"
                    if [[ "$static_owner" == "$class_name" ]]; then
                        local static_value_var="${class_name}_static_${sp}"
                        printf "declare -g %s=%q\n" "$static_value_var" "${!static_value_var}"
                    fi
                done
            fi

            local static_meths_var="${class_name}_class_static_methods"
            if declare -p "$static_meths_var" &>/dev/null; then
                local -n static_meths_ref="$static_meths_var"
                local sm
                for sm in "${static_meths_ref[@]}"; do
                    local static_body_var="${class_name}_static_method_body_${sm}"
                    printf "declare -g %s=%q\n" "$static_body_var" "${!static_body_var}"
                done
            fi
            
            # Get instance template for this specific class
            local template_var="${class_name}_instance_template"
            local template_val="${!template_var}"

            # Emit static property accessors and static methods
            if declare -p "$static_props_var" &>/dev/null; then
                local -n static_props_ref="$static_props_var"
                local -n static_prop_owner_ref="$static_prop_owner_var"
                local sp
                for sp in "${static_props_ref[@]}"; do
                    local static_owner="${static_prop_owner_ref[$sp]:-$class_name}"
                    cat <<STATIC_PROP_EOF
${class_name}.${sp}() {
    if [[ "\$1" == "=" ]]; then
        ${static_owner}_static_${sp}="\$2"
    else
        echo "\${${static_owner}_static_${sp}}"
    fi
}
STATIC_PROP_EOF
                done
            fi

            if declare -p "$static_meths_var" &>/dev/null; then
                local -n static_meths_ref="$static_meths_var"
                local sm
                for sm in "${static_meths_ref[@]}"; do
                    local static_namerefs=""
                    local static_body_var="${class_name}_static_method_body_${sm}"
                    local static_body="${!static_body_var}"
                    if declare -p "$static_props_var" &>/dev/null; then
                        local -n static_props_ref="$static_props_var"
                        local -n static_prop_owner_ref="$static_prop_owner_var"
                        local sp
                        for sp in "${static_props_ref[@]}"; do
                            local static_owner="${static_prop_owner_ref[$sp]:-$class_name}"
                            static_namerefs+="local -n $sp=${static_owner}_static_${sp}; "
                        done
                    fi

                    cat <<STATIC_METH_EOF
${class_name}.${sm}() {
    ${static_namerefs}
    local __tmp_out="\$(mktemp)"
    local __kk_return_set=0
    local __kk_return_value=""
    local __kk_return_silent=1
    {
        ${static_body}
        if (( __kk_return_set )); then
            printf "%s" "\$__kk_return_value"
        fi
    } >"\$__tmp_out"
    REPLY="\$(cat "\$__tmp_out")"
    rm -f "\$__tmp_out"
    printf "%s" "\$REPLY"
}
STATIC_METH_EOF
                done
            fi
            
            # Create optimized constructor with embedded template
            cat <<CONSTRUCTOR_EOF
${class_name}.new() {
    local instname="\$1"
    shift
    [[ "\$instname" =~ ^[A-Za-z_][A-Za-z0-9_]*$ ]] || { echo "Invalid instance name: \$instname" >&2; return 1; }
    local __kk_abstract_var="${class_name}_class_abstract"
    if [[ "\${!__kk_abstract_var:-0}" == "1" ]]; then
        echo "Abstract class '${class_name}' cannot be instantiated" >&2
        return 1
    fi
    local instance_template=$(printf '%q' "$template_val")
    source <(sed "s/__INST__/\$instname/g" <<< "\$instance_template")

    local __kk_constructor_var="${class_name}_constructor_body"
    if [[ -n "\${!__kk_constructor_var:-}" ]]; then
        local __inst__="\$instname"
        \${instname}._constructor_exec "${class_name}" "\$@"
    fi
}

${class_name}.constructor() {
    local __kk_constructor_var="${class_name}_constructor_body"
    if [[ -n "\${!__kk_constructor_var:-}" ]]; then
        eval "\${!__kk_constructor_var}"
    fi
}
CONSTRUCTOR_EOF
            echo ""
            
        } >> "$output_file"
    done
    
    # Add footer
    cat >> "$output_file" <<EOF

# Compiled classes: ${class_list[*]}
# Generated: $(date)
# Source: $source_label
EOF
    
    chmod +x "$output_file"
    rm -f "$translated_input"
    
    echo "✓ Compiled ${#class_list[@]} classes to: $output_file"
    echo "  Classes: ${class_list[*]}"
    echo "  Usage: source $output_file && ClassName.new instance_name"
}

# Main
if [[ $# -lt 2 ]]; then
    cat <<'USAGE'
Usage: bash kklass_compiler.sh <input.kk> <output.sh>

Compiles class definitions from input file into optimized bash code.

Example:
    # Compile classes
    bash kklass_compiler.sh my_classes.kk my_classes_compiled.sh
    
    # Use compiled classes
    source my_classes_compiled.sh
    MyClass.new myobj
    myobj.method_name
USAGE
    exit 1
fi

compile_class_file "$1" "$2"
